---

- name: Add zabbix repository
  apt:
    deb: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+bionic_all.deb

- name: Install zabbix
  apt:
    update_cache: yes
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-agent
      - mysql-server
      - python-pip

- name: Install PyMySQL package
  pip:
    name: MySQL-python

- name: Create database
  mysql_db:
    name: zabbix

- name: Create DB user
  mysql_user:
    name: zabbix
    host: localhost
